Repository INDEP2022/f-sigebi, pull requests merged in 2023-06, with the labels that each got.

#1866 feat(CATALOG ): MODULO CATALOG - Documentos Resarsimiento #1821
  src/app/pages/catalogs/delegations/delegation-form/delegation-form.component.html
  src/app/pages/catalogs/delegations/delegation-form/delegation-form.component.ts
Labels: bug

#1880 feat(CATALOG)- SIGEBI-Catálogos- Delegaciones. 2.- No funciona selector de CVE Estado y zona geográfica
  src/app/pages/catalogs/delegations/delegation-form/delegation-form.component.html
  src/app/pages/catalogs/delegations/delegation-form/delegation-form.component.ts
Labels: bug

#1882 feat(SIGEBI): SIGEBI-Catálogos- Delegaciones. 5.- Nombres de campos erroneos
  src/app/pages/catalogs/delegations/delegation-form/delegation-form.component.html
  src/app/pages/catalogs/delegations/delegation-list/delegation-columns.ts
Labels: bug

#1885 feat(CATALOG): SIGEBI-Catálogos- Generales. Concepto de pagos 1. Agregar acento.
  src/app/pages/catalogs/payment-concept/payment-concept-detail/payment-concept-detail.component.ts
  src/app/pages/catalogs/payment-concept/payment-concept-list/payment-concept-list.component.ts
Labels: bug

#1919 feat(CATALOG)1: SIGEBI-Catálogos- Delegaciones. 4. Error en registros por página.
  src/app/common/repository/repository.ts
  src/app/core/models/catalogs/zone-geographic.model.ts
  src/app/core/services/catalogs/delegation.service.ts
  src/app/pages/catalogs/delegations/delegation-form/delegation-form.component.html
  src/app/pages/catalogs/delegations/delegation-form/delegation-form.component.ts
  src/app/pages/catalogs/delegations/delegation-list/delegation-columns.ts
  src/app/pages/catalogs/delegations/delegation-list/delegation-list.component.html
  src/app/pages/catalogs/delegations/delegation-list/delegation-list.component.ts
Labels: bug

#1921 feat(CATALOG): SIGEBI-Catálogos- General. Tipo Docto. 1.- Números negativos
  src/app/pages/catalogs/type-docto/type-docto-form/type-docto-form.component.html
Labels: bug

#1926 feat(CATALOG)- SIGEBI-Catálogos- General. Respuestas REPUVE. 1.- Quitar búsqueda principal y poner filtro por columna.
  src/app/pages/catalogs/response-repuve/response-repuve-list/response-repuve-columns.ts
  src/app/pages/catalogs/response-repuve/response-repuve-list/response-repuve-list.component.html
  src/app/pages/catalogs/response-repuve/response-repuve-list/response-repuve-list.component.ts
Labels: bug

#1931 feat(CATALOG):Catálogos- General. Párrafos
  src/app/pages/catalogs/paragraphs/paragraphs-list/paragraphs-list.component.html
  src/app/pages/catalogs/paragraphs/paragraphs-list/paragraphs-list.component.ts
Labels: bug

#1943 feat(CATALOG):Catálogos- Deductivas
  src/app/pages/catalogs/deductives/deductives-list/deductive-columns.ts
Labels: bug

#1948 Validaciones
  src/app/pages/catalogs/deductives-verification/deductives-verification-form/deductives-verification-form.component.html
  src/app/pages/catalogs/deductives-verification/deductives-verification-form/deductives-verification-form.component.ts
  src/app/pages/catalogs/indicator-deadlines/indicator-deadlines-form/indicator-deadlines-form.component.html
  src/app/pages/catalogs/regulatory/regulatory-list/regulatory-list.component.html
Labels: bug

#1949 Catálogo Estado
  src/app/pages/catalogs/states/states-list/states-columns.ts
  src/app/pages/catalogs/states/states-list/states-list.component.ts
Labels: bug

#1953 Catálogos- General. Gavetas
  src/app/core/models/catalogs/regulatory.model.ts
  src/app/pages/catalogs/drawers/drawers-list/drawers-list.component.html
  src/app/pages/catalogs/drawers/drawers-list/drawers-list.component.ts
  src/app/pages/catalogs/regulatory/regulatory-form/regulatoy-form.component.html
  src/app/pages/catalogs/regulatory/regulatory-form/regulatoy-form.component.ts
Labels: bug

#1952 feat(CATALOG)- SIGEBI-Catálogos- General. SssubTipo Bien. 2.- No se puede modificar.
  src/app/pages/catalogs/good-sssubtypes/good-sssubtypes-form/good-sssubtypes-form.component.ts
  src/app/pages/catalogs/good-sssubtypes/good-sssubtypes-list/good-sssubtype-columns.ts
  src/app/pages/catalogs/good-sssubtypes/good-sssubtypes-list/good-sssubtypes-list.component.html
  src/app/pages/catalogs/good-sssubtypes/good-sssubtypes-list/good-sssubtypes-list.component.ts
Labels: bug

#1971 Cat_Regulaciones
  src/app/common/repository/repository.ts
  src/app/core/models/catalogs/regulatory.model.ts
  src/app/core/services/catalogs/regulatory.service.ts
  src/app/pages/catalogs/regulatory/regulatory-form/regulatoy-form.component.html
  src/app/pages/catalogs/regulatory/regulatory-form/regulatoy-form.component.ts
  src/app/pages/catalogs/regulatory/regulatory-list/regulatory-columns.ts
Labels: bug

#1974 feat(CATALOG): fix
  src/app/pages/catalogs/good-sssubtypes/good-sssubtypes-form/good-sssubtypes-form.component.ts
  src/app/pages/catalogs/good-sssubtypes/good-sssubtypes-list/good-sssubtype-columns.ts
  src/app/pages/catalogs/good-sssubtypes/good-sssubtypes-list/good-sssubtypes-list.component.ts
Labels: bug

#1975 feat(CATALOG): SIGEBI-Catálogos- General. Municipios 3.-No se permiten números negativos.
  src/app/pages/catalogs/municipalities/municipality-form/municipality-form.component.html
Labels: bug

#1976 feat(CATALOG): SIGEBI-Catálogos- General. Municipios 1.- Quitar búsqueda general y anexar filtrado por columna.
  src/app/@standalone/shared-forms/scan-file-shared/scan-file-shared.component.ts
  src/app/pages/catalogs/municipalities/municipality-form/municipality-form.component.html
  src/app/pages/catalogs/municipalities/municipality-form/municipality-form.component.ts
  src/app/pages/catalogs/municipalities/municipality-list/municipality-columns.ts
  src/app/pages/catalogs/municipalities/municipality-list/municipality-list.component.html
  src/app/pages/catalogs/municipalities/municipality-list/municipality-list.component.ts
  src/app/pages/judicial-physical-reception/cancellation-recepcion/cancellation-recepcion.component.ts
  src/app/pages/judicial-physical-reception/confiscated-records/confiscated-records.component.ts
  src/app/pages/judicial-physical-reception/confiscated-records/settings-tables.ts
Labels: bug

#1977 feat(CATALOG): SIGEBI-Catálogos- General. Respuestas REPUVE. 2.- No d…
  src/app/common/repository/repository.ts
  src/app/core/services/catalogs/response-repuve.service.ts
Labels: bug

#1978 feat(CATALOG): SIGEBI-Cátalogos-Normas - Al crear un registro no todo…
  src/app/pages/catalogs/norms/norms-form/norms-form.component.ts
  src/app/pages/catalogs/type-services/type-services-form/type-services-form.component.ts
Labels: bug

#1981 Cat-Clarifica-regulatory-deduvtive
  src/app/pages/catalogs/clarifications/clarifications-detail/clarifications-detail.component.html
  src/app/pages/catalogs/clarifications/clarifications-detail/clarifications-detail.component.ts
  src/app/pages/catalogs/clarifications/clarifications-list/clarification-columns.ts
  src/app/pages/catalogs/deductives/deductives-list/deductive-columns.ts
  src/app/pages/catalogs/regulatory/regulatory-list/regulatory-columns.ts
Labels: bug

#2006 feat(CATALOG): SIGEBI-Catálogos- General. Lista Fracciones. 4. No dej…
  src/app/pages/catalogs/fractions/fractions-form/fractions-form.component.html
  src/app/pages/catalogs/fractions/fractions-form/fractions-form.component.ts
  src/app/pages/catalogs/fractions/fractions-list/fractions-columns.ts
  src/app/pages/catalogs/fractions/fractions-list/fractions-list.component.ts
Labels: bug

#2007 feat(CATALOG): SIGEBI-Catálogos- General. Lista Fracciones. 3.- Error…
  src/app/pages/catalogs/fractions/fractions-list/fractions-columns.ts
  src/app/pages/catalogs/fractions/fractions-list/fractions-list.component.html
  src/app/pages/catalogs/fractions/fractions-list/fractions-list.component.ts
Labels: bug

#2010 feat(CATALOG): SIGEBI-Catálogo - DOCUMENTOS RESARCIMIENTO SAT XML - Validad longitud máxima permitida para los campos de entrada
  src/app/pages/catalogs/doc-compensation-sat-xml/doc-compensation-sat-xml-form/doc-compensation-sat-xml-form.component.ts
Labels: bug

#2011 feat(CATALOG): BUGS MANAGEMENT-LEGAL SUPPORT-DOC COMPENSATION
  src/app/common/repository/repository.ts
  src/app/core/services/catalogs/doc-compensation-sat-xml.service.ts
  src/app/core/services/catalogs/management.service.ts
  src/app/pages/catalogs/doc-compensation-sat-xml/doc-compensation-sat-xml-form/doc-compensation-sat-xml-form.component.ts
  src/app/pages/catalogs/legal-support/legal-support-form/legal-support-form.component.html
  src/app/pages/catalogs/legal-support/legal-support-form/legal-support-form.component.ts
  src/app/pages/catalogs/legal-support/legal-support-list/legal-support-list.component.html
  src/app/pages/catalogs/legal-support/legal-support-list/legal-support-list.component.ts
  src/app/pages/catalogs/management/management-form/management-form.component.html
  src/app/pages/catalogs/management/management-form/management-form.component.ts
  src/app/pages/catalogs/management/managements-list/management-columns.ts
  src/app/pages/catalogs/management/managements-list/managements-list.component.html
  src/app/pages/catalogs/management/managements-list/managements-list.component.ts
Labels: bug

#2013 CAT-formalize-programming
  src/app/pages/request/programming-request-components/formalize-programming/columns/minutes-columns.ts
  src/app/pages/request/programming-request-components/formalize-programming/formalize-programming-form/formalize-programmig.data.ts
  src/app/pages/request/programming-request-components/formalize-programming/formalize-programming-form/formalize-programming-form.component.html
  src/app/pages/request/programming-request-components/formalize-programming/formalize-programming.module.ts
  src/app/pages/request/programming-request-components/formalize-programming/information-record/information-record.component.html
  src/app/pages/request/programming-request-components/formalize-programming/information-record/information-record.component.ts
Labels: add

#2009 feat(CATALOG): SIGEBI-Catálogo - DOCUMENTOS RESARCIMIENTO SAT XML - N…
  src/app/pages/catalogs/doc-compensation-sat-xml/doc-compensation-sat-xml-form/doc-compensation-sat-xml-form.component.html
Labels: bug

#2030 feat(CATALOG): bug
  src/app/common/repository/repository.ts
  src/app/core/services/catalogs/save-value.service.ts
  src/app/pages/catalogs/doc-compensation-sat/doc-compensation-sat-form/doc-compensation-sat-form.component.html
  src/app/pages/catalogs/doc-compensation-sat/doc-compensation-sat-form/doc-compensation-sat-form.component.ts
  src/app/pages/catalogs/save-values/save-value-form/save-value-form.component.html
  src/app/pages/catalogs/save-values/save-value-form/save-value-form.component.ts
  src/app/pages/catalogs/save-values/save-values-list/save-values-list.component.html
  src/app/pages/catalogs/save-values/save-values-list/save-values-list.component.ts
Labels: bug

#2044 feat(CATALOG): bugs
  src/app/common/repository/repository.ts
  src/app/pages/catalogs/doc-compensation-sat/doc-compensation-sat-form/doc-compensation-sat-form.component.html
  src/app/pages/catalogs/doc-compensation-sat/doc-compensation-sat-form/doc-compensation-sat-form.component.ts
  src/app/pages/catalogs/doc-compensation-sat/doc-compensation-sat-list/doc-compensation-sat-list.component.ts
Labels: bug

#2049 Develop brayan 24
  src/app/common/repository/repository.ts
  src/app/core/models/catalogs/rate-catalog.model.ts
  src/app/core/services/catalogs/claim-conclusion.service.ts
  src/app/core/services/catalogs/delegation.service.ts
  src/app/core/services/catalogs/rate-catalog.service.ts
  src/app/core/services/catalogs/service-cat.service.ts
  src/app/pages/catalogs/cat-services/cat-services-form/cat-services-form.component.ts
  src/app/pages/catalogs/claim-conclusion/claim-conclusion-form/claim-conclusion-form.component.html
  src/app/pages/catalogs/claim-conclusion/claim-conclusion-form/claim-conclusion-form.component.ts
  src/app/pages/catalogs/claim-conclusion/claim-conclusion-list/claim-conclusion-list.component.html
  src/app/pages/catalogs/claim-conclusion/claim-conclusion-list/claim-conclusion-list.component.ts
  src/app/pages/parameterization/rate-catalog/modal-rates-catalog/modal-rates-catalog.component.html
  src/app/pages/parameterization/rate-catalog/modal-rates-catalog/modal-rates-catalog.component.ts
  src/app/pages/parameterization/rate-catalog/rate-catalog/rate-catalog-columns.ts
  src/app/pages/parameterization/rate-catalog/rate-catalog/rate-catalog.component.html
  src/app/pages/parameterization/rate-catalog/rate-catalog/rate-catalog.component.ts
Labels: bug

#2071 Jeanc dev2.9
  src/app/pages/request/programming-request-components/formalize-programming/formalize-programming.module.ts
  src/app/pages/request/programming-request-components/formalize-programming/information-record/information-record.component.ts
  src/app/pages/request/programming-request-components/formalize-programming/print-report-modal/list-reports-column.ts
  src/app/pages/request/programming-request-components/formalize-programming/print-report-modal/print-report-modal.component.html
  src/app/pages/request/programming-request-components/formalize-programming/print-report-modal/print-report-modal.component.ts
Labels: add

#2101 CAT_FORMALIZE-PROGRAMMING
  src/app/pages/request/programming-request-components/execute-reception/execute-reception-form/columns/transportable-goods-columns.ts
  src/app/pages/request/programming-request-components/execute-reception/execute-reception-form/execute-reception-form.component.html
  src/app/pages/request/programming-request-components/execute-reception/execute-reception-form/execute-reception-form.component.ts
  src/app/pages/request/programming-request-components/formalize-programming/columns/minutes-columns.ts
  src/app/pages/request/programming-request-components/formalize-programming/formalize-programming-form/formalize-programmig.data.ts
  src/app/pages/request/programming-request-components/formalize-programming/formalize-programming-form/formalize-programming-form.component.html
  src/app/pages/request/programming-request-components/formalize-programming/formalize-programming-form/formalize-programming-form.component.ts
Labels: add

#2161 formalize-programming
  src/app/pages/request/programming-request-components/execute-reception/execute-reception-form/columns/transportable-goods-columns.ts
  src/app/pages/request/programming-request-components/formalize-programming/formalize-programming-form/formalize-programming-form.component.html
  src/app/pages/request/programming-request-components/formalize-programming/formalize-programming-form/formalize-programming-form.component.ts
Labels: add

#2193 Bug-13-06
  src/app/pages/request/programming-request-components/acept-programming/acept-programming-form/acept-programming-form.component.ts
  src/app/pages/request/programming-request-components/acept-programming/columns/estate-columns.ts
  src/app/pages/request/programming-request-components/formalize-programming/information-record/information-record.component.html
  src/app/pages/request/programming-request-components/formalize-programming/information-record/information-record.component.ts
  src/app/pages/request/programming-request-components/schedule-notify/schedule-notify-form/schedule-notify-form.component.html
  src/app/pages/request/shared-request/warehouse-form/warehouse-form.component.html
Labels: bug

#2225 feat(BUG): SIGEBI - Catálogos - DOCUMENTOS RESARCIMIENTO SAT - Nombre…
  src/app/pages/catalogs/doc-compensation-sat/doc-compensation-sat-form/doc-compensation-sat-form.component.ts
Labels: bug

#2249 formulariov1.1
  src/app/pages/request/programming-request-components/formalize-programming/information-record/information-record.component.html
  src/app/pages/request/programming-request-components/formalize-programming/information-record/information-record.component.ts
Labels: add

#2260 feat(CATALOG):
  src/app/pages/catalogs/delegations/delegation-list/delegation-columns.ts
Labels: bug

#2394 Jeanc dev2.14
  src/app/pages/request/programming-request-components/acept-programming/acept-programming-form/acept-programming-form.component.html
  src/app/pages/request/programming-request-components/acept-programming/acept-programming-form/acept-programming-form.component.ts
  src/app/pages/request/programming-request-components/acept-programming/columns/estate-columns.ts
  src/app/pages/request/programming-request-components/perform-programming/perform-programming-form/perform-programming-form.component.ts
  src/app/pages/request/programming-request-components/perform-programming/warehouse-select-form/warehouse-select-form.component.ts
Labels: bug

#2391 feat(BUG): agregando filtros multiples por columna ADMINISTRACIÓN BIENES
  src/app/pages/administrative-processes/administration-assets/appointment-data/appointment-data.component.ts
  src/app/pages/administrative-processes/administration-assets/assigned-vaults/assigned-vaults.component.ts
  src/app/pages/administrative-processes/administration-assets/data-valuations/data-valuations.component.ts
  src/app/pages/administrative-processes/administration-assets/household/household.component.ts
  src/app/pages/administrative-processes/administration-assets/income-per-asset/income-per-asset.component.ts
  src/app/pages/administrative-processes/administration-assets/inventory-data/inventory-data.component.ts
  src/app/pages/administrative-processes/administration-assets/registry-services/registry-services.component.ts
  src/app/pages/administrative-processes/administration-assets/secure-data/secure-data.component.ts
  src/app/pages/administrative-processes/administration-assets/warehouses-assigned/warehouses-assigned.component.ts
Labels: bug

#2403 Brayan bugv2
  src/app/pages/administrative-processes/administration-assets/income-per-asset/income-per-asset.component.ts
  src/app/pages/administrative-processes/administration-assets/search-tab/search-tab.component.ts
Labels: bug

#2431 bugs
  src/app/core/models/good-programming/good-programming.ts
  src/app/pages/request/programming-request-components/perform-programming/perform-programming-form/perform-programming-form.component.html
  src/app/pages/request/programming-request-components/perform-programming/perform-programming-form/perform-programming-form.component.ts
  src/app/pages/request/programming-request-components/programming-request.module.ts
  src/app/pages/request/programming-request-components/shared-components-programming/domicile-form/domicile-form.component.html
  src/app/pages/request/programming-request-components/shared-components-programming/domicile-form/domicile-form.component.ts
Labels: bug, add

#2445 Jeanc dev2.18
  src/app/pages/juridical-processes/juridical-ruling-g/juridical-ruling-g/juridical-ruling-g.component.ts
  src/app/pages/juridical-processes/juridical-ruling/juridical-ruling/juridical-ruling.component.ts
  src/app/pages/request/programming-request-components/perform-programming/perform-programming-form/perform-programming-form.component.html
  src/app/pages/request/programming-request-components/perform-programming/perform-programming-form/perform-programming-form.component.ts
  src/app/pages/request/shared-request/warehouse-form/warehouse-form.component.ts
Labels: bug

#2453 bugs
  src/app/pages/request/programming-request-components/acept-programming/acept-programming-form/acept-programming-form.component.ts
  src/app/pages/request/programming-request-components/acept-programming/columns/estate-columns.ts
  src/app/pages/request/programming-request-components/perform-programming/perform-programming-form/perform-programming-form.component.ts
Labels: bug

#2463 Jeanc dev2.19
  src/app/pages/request/programming-request-components/formalize-programming/columns/minutes-columns.ts
  src/app/pages/request/programming-request-components/perform-programming/perform-programming-form/perform-programming-form.component.ts
  src/app/pages/request/programming-request-components/schedule-notify/schedule-notify-form/schedule-notify-form.component.ts
  src/app/pages/request/programming-request-components/shared-components-programming/domicile-form/domicile-form.component.html
  src/app/pages/request/programming-request-components/shared-components-programming/domicile-form/domicile-form.component.ts
  src/app/pages/request/shared-request/warehouse-confirm/warehouse-confirm.component.html
  src/app/pages/request/shared-request/warehouse-confirm/warehouse-confirm.component.ts
Labels: bug

#2481 bug + add
  src/app/common/repository/interfaces/list-params.ts
  src/app/pages/request/programming-request-components/formalize-programming/formalize-programming-form/formalize-programming-form.component.ts
  src/app/pages/request/programming-request-components/perform-programming/perform-programming-form/perform-programming-form.component.ts
  src/app/pages/request/programming-request-components/shared-components-programming/domicile-form/domicile-form.component.html
  src/app/pages/request/programming-request-components/shared-components-programming/domicile-form/domicile-form.component.ts
Labels: bug, add

#2488 Bug#1282
  src/app/pages/administrative-processes/values-per-file/values-per-file/values-per-file.component.ts
Labels: bug

#2502 BUG + ADD
  src/app/common/repository/interfaces/list-params.ts
  src/app/pages/request/programming-request-components/formalize-programming/formalize-programming-form/formalize-programming-form.component.html
  src/app/pages/request/programming-request-components/formalize-programming/formalize-programming-form/formalize-programming-form.component.ts
  src/app/pages/request/programming-request-components/perform-programming/perform-programming-form/perform-programming-form.component.ts
  src/app/pages/request/programming-request-components/shared-components-programming/domicile-form/domicile-form.component.html
  src/app/pages/request/programming-request-components/shared-components-programming/domicile-form/domicile-form.component.ts
Labels: bug, add

#2555 bug+add
  src/app/core/models/good-programming/good-programming.ts
  src/app/pages/catalogs/deductives/deductives-list/deductives-list.component.ts
  src/app/pages/request/programming-request-components/acept-programming/acept-programming-form/acept-programming-form.component.ts
  src/app/pages/request/programming-request-components/acept-programming/columns/estate-columns.ts
  src/app/pages/request/programming-request-components/perform-programming/perform-programming-form/perform-programming-form.component.ts
  src/app/pages/request/programming-request-components/perform-programming/perform-programming-form/settings-tables.ts
  src/app/pages/request/programming-request-components/perform-programming/warehouse-select-form/warehouse-select-form.component.html
  src/app/pages/request/programming-request-components/perform-programming/warehouse-select-form/warehouse-select-form.component.ts
  src/app/pages/request/shared-request/warehouse-confirm/warehouse-confirm.component.ts
  src/app/pages/request/transfer-request/tabs/notify-clarifications-impropriety-tabs-component/upload-fiels-modal/upload-fiels-modal.component.ts
Labels: bug, add

#2559 BUG-CATALOGO
  src/app/pages/catalogs/deductives/deductive-form/deductive-form.component.html
  src/app/pages/request/shared-request/confirm-programming/confirm-programming.component.html
Labels: bug

#2565 Bug-catalogo
  src/app/pages/catalogs/deductives/deductive-form/deductive-form.component.ts
  src/app/pages/catalogs/deductives/deductives-list/deductives-list.component.ts
Labels: bug

#2579 CORREO
  src/app/pages/request/programming-request-components/acept-programming/acept-programming-form/acept-programming-form.component.ts
  src/environments/environment.ts
Labels: bug

#2589 Jeanc dev3.5
  src/app/pages/request/programming-request-components/acept-programming/acept-programming-form/acept-programming-form.component.ts
  src/app/pages/request/programming-request-components/acept-programming/columns/estate-columns.ts
  src/app/pages/request/programming-request-components/formalize-programming/print-report-modal/print-report-modal.component.ts
  src/app/pages/request/programming-request-components/perform-programming/perform-programming-form/perform-programming-form.component.ts
  src/app/pages/request/programming-request-components/perform-programming/user-form/user-form.component.html
  src/app/pages/request/transfer-request/tabs/notify-clarifications-impropriety-tabs-component/print-report-modal/print-report-modal.component.ts
Labels: bug

#2601 Bug + add
  src/app/pages/request/programming-request-components/acept-programming/acept-programming-form/acept-programming-form.component.ts
  src/app/pages/request/programming-request-components/perform-programming/perform-programming-form/perform-programming-form.component.html
  src/app/pages/request/programming-request-components/perform-programming/perform-programming-form/perform-programming-form.component.ts
Labels: bug, add

#2613 Jeanc dev1.005
  src/app/pages/request/programming-request-components/acept-programming/acept-programming-form/acept-programming-form.component.ts
  src/app/pages/request/programming-request-components/acept-programming/columns/estate-columns.ts
  src/app/pages/request/programming-request-components/execute-reception/execute-reception-form/columns/transportable-goods-columns.ts
  src/app/pages/request/programming-request-components/execute-reception/show-report-component/show-report-component.component.ts
  src/app/pages/request/programming-request-components/formalize-programming/columns/transportable-goods-columns.ts
  src/app/pages/request/programming-request-components/formalize-programming/print-report-modal/list-reports-column.ts
  src/app/pages/request/programming-request-components/formalize-programming/print-report-modal/print-report-modal.component.html
  src/app/pages/request/programming-request-components/perform-programming/perform-programming-form/perform-programming-form.component.ts
  src/app/pages/request/programming-request-components/return-to-perform-programming/return-to-perform-programming-form/return-to-perform-programming-form.component.ts
  src/app/pages/request/programming-request-components/schedule-reception/search-user-form/search-user-form.component.ts
  src/app/pages/request/programming-request-components/shared-components-programming/domicile-form/domicile-form.component.html
  src/app/pages/request/shared-request/confirm-programming/confirm-programming.component.html
  src/app/pages/request/shared-request/document-form/document-form.component.ts
  src/app/pages/request/shared-request/electronic-signature-list/electronic-signature-columns.ts
  src/app/pages/request/shared-request/electronic-signature-list/electronic-signature-list.component.html
  src/app/pages/request/shared-request/sign-report/columns.ts
  src/app/pages/request/transfer-request/tabs/notify-clarifications-impropriety-tabs-component/print-report-modal/print-report-modal.component.html
  src/app/pages/request/transfer-request/tabs/notify-clarifications-impropriety-tabs-component/upload-fiels-modal/upload-fiels-modal.component.ts
Labels: bug, add
