Repository INDEP2022/f-sigebi, pull requests merged in 2023-07, with the labels that each got.

#2637 cambio+BUG
  src/app/core/shared/patterns.ts
  src/app/pages/catalogs/deductives/deductive-form/deductive-form.component.ts
  src/app/pages/catalogs/deductives/deductives-list/deductive-columns.ts
  src/app/pages/request/programming-request-components/acept-programming/acept-programming-form/acept-programming-form.component.ts
  src/app/pages/request/programming-request-components/acept-programming/columns/estate-columns.ts
  src/app/pages/request/programming-request-components/perform-programming/perform-programming-form/perform-programming-form.component.html
  src/app/pages/request/programming-request-components/perform-programming/perform-programming-form/perform-programming-form.component.ts
  src/app/pages/request/programming-request-components/perform-programming/user-form/user-form.component.ts
  src/app/pages/request/programming-request-components/schedule-reception/search-user-form/search-user-form.component.ts
  src/app/pages/request/programming-request-components/shared-components-programming/domicile-form/domicile-form.component.ts
Labels: bug, add

#2672 catalogo-bugv1
  src/app/pages/catalogs/opinions/opinions-list/opinion-columns.ts
  src/app/pages/catalogs/opinions/opinions-list/opinions-list.component.ts
Labels: bug

#2673 correccion
  src/app/pages/request/programming-request-components/acept-programming/columns/estate-columns.ts
Labels: bug

#2738 Programming module
  .vscode/settings.json
  src/app/pages/request/programming-request-components/acept-programming/acept-programming-form/acept-programming-form.component.html
  src/app/pages/request/programming-request-components/acept-programming/acept-programming-form/acept-programming-form.component.ts
  src/app/pages/request/programming-request-components/acept-programming/columns/estate-columns.ts
  src/app/pages/request/programming-request-components/execute-reception/execute-reception-form/execute-reception-form.component.html
  src/app/pages/request/programming-request-components/execute-reception/execute-reception-form/execute-reception-form.component.ts
  src/app/pages/request/programming-request-components/execute-reception/show-report-component/show-report-component.component.html
  src/app/pages/request/programming-request-components/formalize-programming/formalize-programming-form/formalize-programming-form.component.html
  src/app/pages/request/programming-request-components/perform-programming/perform-programming-form/perform-programming-form.component.html
  src/app/pages/request/programming-request-components/perform-programming/perform-programming-form/perform-programming-form.component.ts
  src/app/pages/request/programming-request-components/perform-programming/user-form/user-form.component.html
  src/app/pages/request/programming-request-components/schedule-notify/schedule-notify-form/schedule-notify-form.component.html
  src/app/pages/request/programming-request-components/schedule-reception/schedule-reception-form/schedule-reception-form.component.html
  src/app/pages/request/programming-request-components/schedule-reception/schedule-reception-form/schedule-reception-form.component.ts
  src/app/pages/request/programming-request-components/schedule-reception/search-user-form/search-user-form.component.html
  src/app/pages/request/programming-request-components/shared-components-programming/domicile-form/domicile-form.component.html
  src/app/pages/request/programming-request-components/shared-components-programming/reject-programming-form/reject-programming-form.component.html
  src/app/pages/request/shared-request/assign-receipt-form/assign-receipt-form.component.html
  src/app/pages/request/shared-request/confirm-programming/confirm-programming.component.html
  src/app/pages/request/shared-request/generate-receipt-form/generate-receipt-form.component.html
  src/app/pages/request/shared-request/generate-receipt-form/generate-receipt-form.component.ts
  src/app/pages/request/shared-request/warehouse-confirm/warehouse-confirm.component.html
  src/app/pages/request/shared-request/warehouse-confirm/warehouse-confirm.component.ts
  src/app/pages/request/shared-request/warehouse-form/warehouse-form.component.html
  src/app/pages/request/shared-request/warehouse-show/warehouse-show.component.html
  src/app/pages/request/transfer-request/tabs/notify-clarifications-impropriety-tabs-component/upload-fiels-modal/upload-fiels-modal.component.html
  src/app/pages/siab-web/sami/consult-tasks/consult-tasks/consult-tasks-columns.ts
  src/app/pages/siab-web/sami/consult-tasks/consult-tasks/consult-tasks.component.html
Labels: add
